''' Betfair names '''

countries = {
    "Arsenal":"England",
    "Aston Villa":"England",
    "Bournemouth":"England",
    "Brentford":"England",
    "Brighton":"England",
    "Burnley":"England",
    "Chelsea":"England",
    "Crystal Palace":"England",
    "Everton":"England",
    "Fulham":"England",
    "Liverpool":"England",
    "Luton":"England",
    "Man City":"England",
    "Man Utd":"England",
    "Newcastle":"England",
    "Nottm Forest":"England",
    "Sheff Utd":"England",
    "Tottenham":"England",
    "West Ham":"England",
    "Wolves":"England",


    "Birmingham":"England",
    "Blackburn":"England",
    "Bristol City":"England",
    "Cardiff":"England",
    "Coventry":"England",
    "Huddersfield":"England",
    "Hull":"England",
    "Ipswich":"England",
    "Leeds":"England",
    "Leicester":"England",
    "Middlesbrough":"England",
    "Millwall":"England",
    "Norwich":"England",
    "Plymouth":"England",
    "Preston":"England",
    "QPR":"England",
    "Rotherham":"England",
    "Sheff Wed":"England",
    "Southampton":"England",
    "Stoke":"England",
    "Sunderland":"England",
    "Swansea":"England",
    "Watford":"England",
    "West Brom":"England",


    "Barnsley":"England",
    "Blackpool":"England",
    "Bolton":"England",
    "Bristol Rovers":"England",
    "Burton Albion":"England",
    "Cambridge Utd":"England",
    "Carlisle":"England",
    "Charlton":"England",
    "Cheltenham":"England",
    "Derby":"England",
    "Exeter":"England",
    "Fleetwood Town":"England",
    "Leyton Orient":"England",
    "Lincoln":"England",
    "Northampton":"England",
    "Oxford Utd":"England",
    "Peterborough":"England",
    "Port Vale":"England",
    "Portsmouth":"England",
    "Reading":"England",
    "Shrewsbury":"England",
    "Stevenage":"England",
    "Wigan":"England",
    "Wycombe":"England",

    "AFC Wimbledon":"England",
    "Accrington":"England",
    "Barrow":"England",
    "Bradford":"England",
    "Colchester":"England",
    "Crawley":"England",
    "Crewe":"England",
    "Doncaster":"England",
    "Forest Green":"England",
    "Gillingham":"England",
    "Grimsby":"England",
    "Harrogate Town":"England",
    "Mansfield":"England",
    "MK Dons":"England",
    "Morecambe":"England",
    "Newport County":"England",
    "Notts Co":"England",
    "Salford City":"England",
    "Stockport":"England",
    "Sutton Utd":"England",
    "Swindon":"England",
    "Tranmere":"England",
    "Walsall":"England",
    "Wrexham":"England",

    "AFC Fylde":"England",
    "Aldershot":"England",
    "Altrincham":"England",
    "Barnet":"England",
    "Boreham Wood":"England",
    "Bromley":"England",
    "Chesterfield":"England",
    "Dag and Red":"England",
    "Dorking Wanderers":"England",
    "Eastleigh":"England",
    "Ebbsfleet Utd":"England",
    "FC Halifax Town":"England",
    "Gateshead":"England",
    "Hartlepool":"England",
    "Kidderminster":"England",
    "Maidenhead":"England",
    "Oldham":"England",
    "Oxford City":"England",
    "Rochdale":"England",
    "Solihull Moors":"England",
    "Southend":"England",
    "Wealdstone":"England",
    "Woking":"England",
    "York City":"England",

    "Alaves":"Spain",
    "Almeria":"Spain",
    "Athletic Bilbao":"Spain",
    "Atletico Madrid":"Spain",
    "Barcelona":"Spain",
    "Cadiz":"Spain",
    "Celta Vigo":"Spain",
    "Getafe":"Spain",
    "Girona":"Spain",
    "Granada":"Spain",
    "Las Palmas":"Spain",
    "Mallorca":"Spain",
    "Osasuna":"Spain",
    "Rayo Vallecano":"Spain",
    "Betis":"Spain",
    "Real Madrid":"Spain",
    "Real Sociedad":"Spain",
    "Sevilla":"Spain",
    "Valencia":"Spain",
    "Villarreal":"Spain",

    "Albacete":"Spain",
    "Alcorcon":"Spain",
    "Amorebieta":"Spain",
    "Burgos":"Spain",
    "Eibar":"Spain",
    "Elche":"Spain",
    "Eldense":"Spain",
    "Espanyol":"Spain",
    "Andorra CF":"Spain",
    "FC Cartagena":"Spain",
    "Huesca":"Spain",
    "Leganes":"Spain",
    "Levante":"Spain",
    "Mirandes":"Spain",
    "Oviedo":"Spain",
    "Racing de Ferrol":"Spain",
    "Racing Santander":"Spain",
    "Sporting Gijon":"Spain",
    "Tenerife":"Spain",
    "Valladolid":"Spain",
    "Villarreal B":"Spain",
    "Zaragoza":"Spain",
    
    "AC Milan":"Italy",
    "Roma":"Italy",
    "Atalanta":"Italy",
    "Bologna":"Italy",
    "Cagliari":"Italy",
    "Empoli":"Italy",
    "Fiorentina":"Italy",
    "Frosinone":"Italy",
    "Genoa":"Italy",
    "Inter":"Italy",
    "Juventus":"Italy",
    "Lazio":"Italy",
    "Lecce":"Italy",
    "AC Monza":"Italy",
    "Napoli":"Italy",
    "Salernitana":"Italy",
    "Sassuolo":"Italy",
    "Torino":"Italy",
    "Udinese":"Italy",
    "Verona":"Italy",

    "Ascoli":"Italy",
    "Bari":"Italy",
    "Brescia":"Italy",
    "Catanzaro":"Italy",
    "Cittadella":"Italy",
    "Como":"Italy",
    "Cosenza":"Italy",
    "US Cremonese":"Italy",
    "Feralpisalo":"Italy",
    "Lecco":"Italy",
    "Modena":"Italy",
    "Palermo":"Italy",
    "Parma":"Italy",
    "Pisa":"Italy",
    "Reggiana":"Italy",
    "Sampdoria":"Italy",
    "Spezia":"Italy",
    "Sudtirol":"Italy",
    "Ternana":"Italy",
    "Venezia":"Italy",

    "FC Koln":"Germany",
    "Hoffenheim":"Germany",
    "Leverkusen":"Germany",
    "Bayern Munich":"Germany",
    "Dortmund":"Germany",
    "Mgladbach":"Germany",
    "Eintracht Frankfurt":"Germany",
    "Augsburg":"Germany",
    "FC Heidenheim":"Germany",
    "Mainz":"Germany",
    "RB Leipzig":"Germany",
    "Freiburg":"Germany",
    "SV Darmstadt":"Germany",
    "Union Berlin":"Germany",
    "Stuttgart":"Germany",
    "Bochum":"Germany",
    "Wolfsburg":"Germany",
    "Werder Bremen":"Germany",

    "Clermont":"France",
    "Le Havre":"France",
    "Lens":"France",
    "Lille":"France",
    "Lorient":"France",
    "Lyon":"France",
    "Marseille":"France",
    "Metz":"France",
    "Monaco":"France",
    "Montpellier":"France",
    "Nantes":"France",
    "Nice":"France",
    "Paris St-G":"France",
    "Reims":"France",
    "Rennes":"France",
    "Brest":"France",
    "Strasbourg":"France",
    "Toulouse":"France",
    
    "AS Eupen":"Belgium",
    "Anderlecht":"Belgium",
    "Antwerp":"Belgium",
    "Cercle Brugge":"Belgium",
    "Charleroi":"Belgium",
    "Club Brugge KV":"Belgium",
    "Genk":"Belgium",
    "Gent":"Belgium",
    "KV Mechelen":"Belgium",
    "KVC Westerlo":"Belgium",
    "Kortrijk":"Belgium",
    "OH Leuven":"Belgium",
    "RWDM":"Belgium",
    "St. Truiden":"Belgium",
    "Standard Liege":"Belgium",
    "Union St. Gilloise":"Belgium",

    "Az Alkmaar":"Netherlands",
    "Ajax":"Netherlands",
    "Almere City":"Netherlands",
    "Excelsior":"Netherlands",
    "FC Volendam":"Netherlands",
    "Feyenoord":"Netherlands",
    "Fortuna Sittard":"Netherlands",
    "Go Ahead Eagles":"Netherlands",
    "Heerenveen":"Netherlands",
    "Heracles":"Netherlands",
    "NEC Nijmegen":"Netherlands",
    "PEC Zwolle":"Netherlands",
    "PSV":"Netherlands",
    "Sparta Rotterdam":"Netherlands",
    "FC Twente":"Netherlands",
    "FC Utrecht":"Netherlands",
    "Vitesse Arnhem":"Netherlands",
    "RKC Waalwijk":"Netherlands",

    "Ajaccio":"France",
    "Amiens":"France",
    "Angers":"France",
    "Annecy":"France",
    "Auxerre":"France",
    "Bastia":"France",
    "Bordeaux":"France",
    "Caen":"France",
    "Concarneau":"France",
    "Dunkerque":"France",
    "Estac Troyes":"France",
    "Grenoble":"France",
    "Guingamp":"France",
    "Laval":"France",
    "PAU":"France",
    "Paris FC":"France",
    "Quevilly":"France",
    "Rodez":"France",
    "Saint Etienne":"France",
    "Valenciennes":"France",

    "Braunschweig":"Germany",
    "Kaiserslautern":"Germany",
    "FC Magdeburg":"Germany",
    "Nurnberg":"Germany",
    "Schalke 04":"Germany",
    "St Pauli":"Germany",
    "Fortuna Dusseldorf":"Germany",
    "Hamburger SV":"Germany",
    "Hannover":"Germany",
    "Hansa Rostock":"Germany",
    "Hertha Berlin":"Germany",
    "Holstein Kiel":"Germany",
    "Karlsruhe":"Germany",
    "Paderborn":"Germany",
    "Elversberg":"Germany",
    "Wehen Wiesbaden":"Germany",
    "Greuther Furth":"Germany",
    "VFL Osnabruck":"Germany",

    "Arouca":"Portugal",
    "Benfica":"Portugal",
    "Boavista":"Portugal",
    "Casa Pia":"Portugal",
    "Chaves":"Portugal",
    "Estoril Praia":"Portugal",
    "Club Football Estrela":"Portugal",
    "Porto":"Portugal",
    "Famalicao":"Portugal",
    "Farense":"Portugal",
    "GIL Vicente":"Portugal",
    "Guimaraes":"Portugal",
    "Moreirense":"Portugal",
    "Portimonense":"Portugal",
    "Rio Ave":"Portugal",
    "Braga":"Portugal",
    "Sporting Lisbon":"Portugal",
    "Vizela":"Portugal",

    "Adelaide United":"Australia",
    "Brisbane Roar":"Australia",
    "Central Coast Mariners":"Australia",
    "Macarthur":"Australia",
    "Melbourne City":"Australia",
    "Melbourne Victory":"Australia",
    "Newcastle Jets":"Australia",
    "Perth Glory":"Australia",
    "Sydney":"Australia",
    "Wellington Phoenix":"Australia",
    "Western Sydney Wanderers":"Australia",
    "Western United":"Australia",

    "AIK":"Sweden",
    "BK Hacken":"Sweden",
    "Djurgardens IF":"Sweden",
    "Gais":"Sweden",
    "Halmstads":"Sweden",
    "Hammarby":"Sweden",
    "Brommapojkarna":"Sweden",
    "Elfsborg":"Sweden",
    "IFK Goteborg":"Sweden",
    "Norrkoping":"Sweden",
    "IFK Varnamo":"Sweden",
    "Malmo FF":"Sweden",
    "Mjallby":"Sweden",
    "Sirius":"Sweden",
    "Vasteras SK":"Sweden",
    "kalmar FF":"Sweden",

    "BSC Young Boys":"Switzerland",
    "FC Basel 1893":"Switzerland",
    "FC Lugano":"Switzerland",
    "FC Luzern":"Switzerland",
    "FC ST. Gallen":"Switzerland",
    "FC Winterthur":"Switzerland",
    "FC Zurich":"Switzerland",
    "Grasshoppers":"Switzerland",
    "Lausanne":"Switzerland",
    "Servette FC":"Switzerland",
    "Stade Lausanne-Ouchy":"Switzerland",
    "Yverdon Sport":"Switzerland",
    
    "AGF":"Denmark",
    "Brondby":"Denmark",
    "FC Copenhagen":"Denmark",
    "Midtjylland":"Denmark",
    "FC Nordsjaelland":"Denmark",
    "Hvidovre":"Denmark",
    "Lyngby":"Denmark",
    "Odense":"Denmark",
    "Randers":"Denmark",
    "Silkeborg":"Denmark",
    "Vejle":"Denmark",
    "Viborg":"Denmark",
    
    "Aberdeen":"Scotland",
    "Celtic":"Scotland",
    "Dundee":"Scotland",
    "Hearts":"Scotland",
    "Hibernian":"Scotland",
    "Kilmarnock":"Scotland",
    "Livingston":"Scotland",
    "Motherwell":"Scotland",
    "Rangers":"Scotland",
    "Ross Co":"Scotland",
    "St Johnstone":"Scotland",
    "St Mirren":"Scotland",

    "Abha":"Saudi Arabia",
    "Al Akhdoud":"Saudi Arabia",
    "Al Khaleej Saihat":"Saudi Arabia",
    "Al Riyadh":"Saudi Arabia",
    "Al Shabab":"Saudi Arabia",
    "Al Taawon":"Saudi Arabia",
    "Al Taee":"Saudi Arabia",
    "Al Wehda Club":"Saudi Arabia",
    "Al-Ahli Jeddah":"Saudi Arabia",
    "Al-Ettifaq":"Saudi Arabia",
    "Al-Fateh":"Saudi Arabia",
    "Al-Fayha":"Saudi Arabia",
    "Al-Hazm":"Saudi Arabia",
    "Al-Hilal Saudi FC":"Saudi Arabia",
    "Al-Ittihad FC":"Saudi Arabia",
    "Al-Nassr":"Saudi Arabia",
    "Al-Raed":"Saudi Arabia",
    "Damac":"Saudi Arabia",

    "Atlanta United FC":"USA",
    "Austin":"USA",
    "Charlotte":"USA",
    "Chicago Fire":"USA",
    "Colorado Rapids":"USA",
    "Columbus Crew":"USA",
    "DC United":"USA",
    "FC Cincinnati":"USA",
    "FC Dallas":"USA",
    "Houston Dynamo":"USA",
    "Inter Miami":"USA",
    "Los Angeles FC":"USA",
    "Los Angeles Galaxy":"USA",
    "Minnesota United FC":"USA",
    "Montreal Impact":"USA",
    "Nashville SC":"USA",
    "New England Revolution":"USA",
    "New York City FC":"USA",
    "New York Red Bulls":"USA",
    "Orlando City SC":"USA",
    "Philadelphia Union":"USA",
    "Portland Timbers":"USA",
    "Real Salt Lake":"USA",
    "San Jose Earthquakes":"USA",
    "Seattle Sounders":"USA",
    "Kansas City":"USA",
    "St. Louis City":"USA",
    "Toronto FC":"USA",
    "Vancouver Whitecaps":"USA",

    "America Mineiro":"Brazil",
    "Atletico Paranaense":"Brazil",
    "Atletico-MG":"Brazil",
    "Bahia":"Brazil",
    "Botafogo":"Brazil",
    "Corinthians":"Brazil",
    "Coritiba":"Brazil",
    "Cruzeiro":"Brazil",
    "Cuiaba":"Brazil",
    "Flamengo":"Brazil",
    "Fluminense":"Brazil",
    "Fortaleza EC":"Brazil",
    "Goias":"Brazil",
    "Gremio":"Brazil",
    "Internacional":"Brazil",
    "Palmeiras":"Brazil",
    "RB Bragantino":"Brazil",
    "Santos":"Brazil",
    "Sao Paulo":"Brazil",
    "Vasco DA Gama":"Brazil",

    "Argentinos JRS":"Argentina",
    "Arsenal Sarandi":"Argentina",
    "Atletico Tucuman":"Argentina",
    "Banfield":"Argentina",
    "Barracas Central":"Argentina",
    "Belgrano Cordoba":"Argentina",
    "Boca Juniors":"Argentina",
    "Central Cordoba de Santiago":"Argentina",
    "Colon Santa Fe":"Argentina",
    "Defensa Y Justicia":"Argentina",
    "Estudiantes L.P.":"Argentina",
    "Gimnasia L.P.":"Argentina",
    "Godoy Cruz":"Argentina",
    "Huracan":"Argentina",
    "Independiente":"Argentina",
    "Instituto Cordoba":"Argentina",
    "Lanus":"Argentina",
    "Newells Old Boys":"Argentina",
    "Platense":"Argentina",
    "Racing Club":"Argentina",
    "River Plate":"Argentina",
    "Rosario Central":"Argentina",
    "San Lorenzo":"Argentina",
    "Sarmiento Junin":"Argentina",
    "Talleres Cordoba":"Argentina",
    "Tigre":"Argentina",
    "Union Santa Fe":"Argentina",
    "Velez Sarsfield":"Argentina",

    "Albania":"World",
    "Austria":"World",
    "Belgium":"World",
    "Croatia":"World",
    "CzechRepublic":"World",
    "Denmark":"World",
    "England":"World",
    "France":"World",
    "Georgia":"World",
    "Germany":"World",
    "Hungary":"World",
    "Italy":"World",
    "Netherlands":"World",
    "Poland":"World",
    "Portugal":"World",
    "Romania":"World",
    "Scotland":"World",
    "Serbia":"World",
    "Slovakia":"World",
    "Slovenia":"World",
    "Spain":"World",
    "Switzerland":"World",
    "Turkey":"World",
    "Ukraine":"World",
    "Ukraine":"World"
}

''' Rapid Api on left and Betfair on right'''
teams = {
    "England": {
        "Arsenal":"Arsenal",
        "Aston Villa":"Aston Villa",
        "Bournemouth":"Bournemouth",
        "Brentford":"Brentford",
        "Brighton":"Brighton",
        "Burnley":"Burnley",
        "Chelsea":"Chelsea",
        "Crystal Palace":"Crystal Palace",
        "Everton":"Everton",
        "Fulham":"Fulham",
        "Liverpool":"Liverpool",
        "Luton":"Luton",
        "Manchester City":"Man City",
        "Manchester United":"Man Utd",
        "Newcastle":"Newcastle",
        "Nottingham Forest":"Nottm Forest",
        "Sheffield Utd":"Sheff Utd",
        "Tottenham":"Tottenham",
        "West Ham":"West Ham",
        "Wolves":"Wolves",
        
        "Birmingham":"Birmingham",
        "Blackburn":"Blackburn",
        "Bristol City":"Bristol City",
        "Cardiff":"Cardiff",
        "Coventry":"Coventry",
        "Huddersfield":"Huddersfield",
        "Hull City":"Hull",
        "Ipswich":"Ipswich",
        "Leeds":"Leeds",
        "Leicester":"Leicester",
        "Middlesbrough":"Middlesbrough",
        "Millwall":"Millwall",
        "Norwich":"Norwich",
        "Plymouth":"Plymouth",
        "Preston":"Preston",
        "QPR":"QPR",
        "Rotherham":"Rotherham",
        "Sheffield Wednesday":"Sheff Wed",
        "Southampton":"Southampton",
        "Stoke City":"Stoke",
        "Sunderland":"Sunderland",
        "Swansea":"Swansea",
        "Watford":"Watford",
        "West Brom":"West Brom",

        "Barnsley":"Barnsley",
        "Blackpool":"Blackpool",
        "Bolton":"Bolton",
        "Bristol Rovers":"Bristol Rovers",
        "Burton Albion":"Burton Albion",
        "Cambridge United":"Cambridge Utd",
        "Carlisle":"Carlisle",
        "Charlton":"Charlton",
        "Cheltenham":"Cheltenham",
        "Derby":"Derby",
        "Exeter City":"Exeter",
        "Fleetwood Town":"Fleetwood Town",
        "Leyton Orient":"Leyton Orient",
        "Lincoln":"Lincoln",
        "Northampton":"Northampton",
        "Oxford United":"Oxford Utd",
        "Peterborough":"Peterborough",
        "Port Vale":"Port Vale",
        "Portsmouth":"Portsmouth",
        "Reading":"Reading",
        "Shrewsbury":"Shrewsbury",
        "Stevenage":"Stevenage",
        "Wigan":"Wigan",
        "Wycombe":"Wycombe"
    },
    "Italy": {
        "AC Milan":"AC Milan",
        "AS Roma":"Roma",
        "Atalanta":"Atalanta",
        "Bologna":"Bologna",
        "Cagliari":"Cagliari",
        "Empoli":"Empoli",
        "Fiorentina":"Fiorentina",
        "Frosinone":"Frosinone",
        "Genoa":"Genoa",
        "Inter":"Inter",
        "Juventus":"Juventus",
        "Lazio":"Lazio",
        "Lecce":"Lecce",
        "Monza":"AC Monza",
        "Napoli":"Napoli",
        "Salernitana":"Salernitana",
        "Sassuolo":"Sassuolo",
        "Torino":"Torino",
        "Udinese":"Udinese",
        "Verona":"Verona",
        
        "Ascoli":"Ascoli",
        "Bari":"Bari",
        "Brescia":"Brescia",
        "Catanzaro":"Catanzaro",
        "Cittadella":"Cittadella",
        "Como":"Como",
        "Cosenza":"Cosenza",
        "Cremonese":"US Cremonese",
        "Feralpisalo":"Feralpisalo",
        "Lecco":"Lecco",
        "Modena":"Modena",
        "Palermo":"Palermo",
        "Parma":"Parma",
        "Pisa":"Pisa",
        "Reggiana":"Reggiana",
        "Sampdoria":"Sampdoria",
        "Spezia":"Spezia",
        "Sudtirol":"Sudtirol",
        "Ternana":"Ternana",
        "Venezia":"Venezia"
    },
    "Belgium": {
        "AS Eupen":"Eupen",
        "Anderlecht":"Anderlecht",
        "Antwerp":"Antwerp",
        "Cercle Brugge":"Cercle Brugge",
        "Charleroi":"Charleroi",
        "Club Brugge KV":"Club Brugge",
        "Genk":"Genk",
        "Gent":"Gent",
        "KV Mechelen":"Yellow-Red Mechelen",
        "KVC Westerlo":"Westerlo",
        "Kortrijk":"Kortrijk",
        "OH Leuven":"Oud-Heverlee Leuven",
        "RWDM":"RWDM",# Needs checking
        "St. Truiden":"Sint Truiden",
        "Standard Liege":"Standard",# Needs checking?
        "Union St. Gilloise":"Union St-Gilloise"
    },
    "Netherlands": {
        "AZ Alkmaar":"AZ Alkmaar",
        "Ajax":"Ajax",
        "Almere City FC":"Almere City",
        "Excelsior":"Excelsior",
        "FC Volendam":"FC Volendam",
        "Feyenoord":"Feyenoord",
        "Fortuna Sittard":"Fortuna Sittard",
        "GO Ahead Eagles":"Go Ahead Eagles",
        "Heerenveen":"Heerenveen",
        "Heracles":"Heracles",
        "NEC Nijmegen":"NEC Nijmegen",
        "PEC Zwolle":"PEC Zwolle",
        "PSV Eindhoven":"PSV",
        "Sparta Rotterdam":"Sparta Rotterdam",
        "Twente":"FC Twente",
        "Utrecht":"FC Utrecht",
        "Vitesse":"Vitesse Arnhem",
        "Waalwijk":"RKC Waalwijk"
    },
    "Spain": {
        "Alaves":"Alaves",
        "Almeria":"Almeria",
        "Athletic Club":"Athletic Bilbao",
        "Atletico Madrid":"Atletico Madrid",
        "Barcelona":"Barcelona",
        "Cadiz":"Cadiz",
        "Celta Vigo":"Celta Vigo",
        "Getafe":"Getafe",
        "Girona":"Girona",
        "Granada CF":"Granada",
        "Las Palmas":"Las Palmas",
        "Mallorca":"Mallorca",
        "Osasuna":"Osasuna",
        "Rayo Vallecano":"Rayo Vallecano",
        "Real Betis":"Betis",
        "Real Madrid":"Real Madrid",
        "Real Sociedad":"Real Sociedad",
        "Sevilla":"Sevilla",
        "Valencia":"Valencia",
        "Villarreal":"Villarreal",
        
        "Albacete":"Albacete",
        "Alcorcon":"Alcorcon",
        "Amorebieta":"Amorebieta",
        "Burgos":"Burgos",
        "Eibar":"Eibar",
        "Elche":"Elche",
        "Eldense":"Eldense",
        "Espanyol":"Espanyol",
        "FC Andorra":"Andorra CF",
        "FC Cartagena":"FC Cartagena",
        "Huesca":"Huesca",
        "Leganes":"Leganes",
        "Levante":"Levante",
        "Mirandes":"Mirandes",
        "Oviedo":"Oviedo",
        "Racing Ferrol":"Racing Ferrol",
        "Racing Santander":"Racing Santander",
        "Sporting Gijon":"Sporting Gijon",
        "Tenerife":"Tenerife",
        "Valladolid":"Valladolid",
        "Villarreal II":"Villarreal B",
        "Zaragoza":"Zaragoza"
    },
    "Germany": {
        "1.FC Köln":"FC Koln",
        "1899 Hoffenheim":"Hoffenheim",
        "Bayer Leverkusen":"Leverkusen",
        "Bayern Munich":"Bayern Munich",
        "Borussia Dortmund":"Dortmund",
        "Borussia Monchengladbach":"Mgladbach",
        "Eintracht Frankfurt":"Eintracht Frankfurt",
        "FC Augsburg":"Augsburg",
        "FC Heidenheim":"FC Heidenheim",
        "FSV Mainz 05":"Mainz",
        "RB Leipzig":"RB Leipzig",
        "SC Freiburg":"Freiburg",
        "SV Darmstadt 98":"SV Darmstadt",
        "Union Berlin":"Union Berlin",
        "VfB Stuttgart":"Stuttgart",
        "Vfl Bochum":"Bochum",
        "VfL Wolfsburg":"Wolfsburg",
        "Werder Bremen":"Werder Bremen",
        
        "Eintracht Braunschweig":"Braunschweig",
        "FC Kaiserslautern":"Kaiserslautern",
        "FC Magdeburg":"FC Magdeburg",
        "FC Nurnberg":"Nurnberg",
        "FC Schalke 04":"Schalke 04",
        "FC St. Pauli":"St Pauli",
        "Fortuna Dusseldorf":"Fortuna Dusseldorf",
        "Hamburger SV":"Hamburger SV",
        "Hannover 96":"Hannover",
        "Hansa Rostock":"Hansa Rostock",
        "Hertha Berlin":"Hertha Berlin",
        "Holstein Kiel":"Holstein Kiel",
        "Karlsruher SC":"Karlsruhe",
        "SC Paderborn 07":"Paderborn",
        "SV Elversberg":"Elversberg",
        "SV Wehen":"Wehen Wiesbaden",
        "SpVgg Greuther Furth":"Greuther Furth",
        "VfL Osnabruck":"VFL Osnabruck"
    },
    "Portugal": {
        "Arouca":"Arouca",
        "Benfica":"Benfica",
        "Boavista":"Boavista",
        "Casa Pia":"Casa Pia",
        "Chaves":"Chaves",
        "Estoril":"Estoril Praia",
        "Estrela":"Club Football Estrela",
        "FC Porto":"Porto",
        "Famalicao":"Famalicao",
        "Farense":"Farense",
        "GIL Vicente":"GIL Vicente",
        "Guimaraes":"Guimaraes",
        "Moreirense":"Moreirense",
        "Portimonense":"Portimonense",
        "Rio Ave":"Rio Ave",
        "SC Braga":"Braga",
        "Sporting CP":"Sporting Lisbon",
        "Vizela":"Vizela"
    },
    "France": {
        "Clermont Foot":"Clermont",
        "LE Havre":"Le Havre",
        "Lens":"Lens",
        "Lille":"Lille",
        "Lorient":"Lorient",
        "Lyon":"Lyon",
        "Marseille":"Marseille",
        "Metz":"Metz",
        "Monaco":"Monaco",
        "Montpellier":"Montpellier",
        "Nantes":"Nantes",
        "Nice":"Nice",
        "Paris Saint Germain":"Paris St-G",
        "Reims":"Reims",
        "Rennes":"Rennes",
        "Stade Brestois 29":"Brest",
        "Strasbourg":"Strasbourg",
        "Toulouse":"Toulouse",
        
        "Ajaccio":"AC Ajaccio",
        "Amiens":"Amiens",
        "Angers":"Angers",
        "Annecy":"Annecy",
        "Auxerre":"Auxerre",
        "Bastia":"Bastia",
        "Bordeaux":"Bordeaux",
        "Caen":"Caen",
        "Concarneau":"Concarneau",
        "Dunkerque":"Dunkerque",
        "Estac Troyes":"ESTAC Troyes",
        "Grenoble":"Grenoble",
        "Guingamp":"Guingamp",
        "Laval":"Laval",
        "PAU":"Pau",
        "Paris FC":"Paris FC",
        "Quevilly":"Quevilly Rouen",
        "Rodez":"Rodez",
        "Saint Etienne":"St Etienne",
        "Valenciennes":"Valenciennes"
    },
    "Australia": {
        "Adelaide United":"Adelaide United",
        "Brisbane Roar":"Brisbane Roar",
        "Central Coast Mariners":"Central Coast Mariners",
        "Macarthur":"Macarthur FC",
        "Melbourne City":"Melbourne City",
        "Melbourne Victory":"Melbourne Victory",
        "Newcastle Jets":"Newcastle Jets",
        "Perth Glory":"Perth Glory",
        "Sydney":"Sydney FC",
        "Wellington Phoenix":"Wellington Phoenix",
        "Western Sydney Wanderers":"Western Sydney Wanderers",
        "Western United":"Western United"
    },
    "Sweden": {
        "AIK stockholm":"AIK",
        "BK Hacken":"Hacken",
        "Djurgardens IF":"Djurgardens",
        "Gais":"GAis",
        "Halmstad":"Halmstads",
        "Hammarby FF":"Hammarby",
        "IF Brommapojkarna":"Brommapojkarna",
        "IF elfsborg":"Elfsborg",
        "IFK Goteborg":"IFK Goteborg",
        "IFK Norrkoping":"Norrkoping",
        "IFK Varnamo":"Varnamo",
        "Malmo FF":"Malmo FF",
        "Mjallby AIF":"Mjallby",
        "Sirius":"Sirius",
        "Vasteras SK FK":"Vasteras SK",
        "kalmar FF":"Kalmar FF",
    },
    "Switzerland": {
        "BSC Young Boys":"Young Boys",
        "FC Basel 1893":"FC Basel",
        "FC Lugano":"Lugano",
        "FC Luzern":"Luzern",
        "FC ST. Gallen":"St Gallen",
        "FC Winterthur":"Winterthur",
        "FC Zurich":"FC Zurich",
        "Grasshoppers":"Grasshoppers Zurich",
        "Lausanne":"Lausanne",
        "Servette FC":"Servette",
        "Stade Lausanne-Ouchy":"Stade Lausanne-Ouchy",
        "Yverdon Sport":"Yverdon Sport",
    },
    "Denmark": {
        "Aarhus":"AGF",
        "Brondby":"Brondby",
        "FC Copenhagen":"FC Copenhagen",
        "FC Midtjylland":"Midtjylland",
        "FC Nordsjaelland":"FC Nordsjaelland",
        "Hvidovre":"Hvidovre",
        "Lyngby":"Lyngby",
        "Odense":"Odense",
        "Randers FC":"Randers",
        "Silkeborg":"Silkeborg",
        "Vejle":"Vejle",
        "Viborg":"Viborg"
    },
    "Saudi-Arabia": {
        "Abha":"Abha",
        "Al Akhdoud":"Al-Akldoud",
        "Al Khaleej Saihat":"Al-Khaleej Saihat",
        "Al Riyadh":"Al Riyadh SC",
        "Al Shabab":"Al-Shabab (KSA)",
        "Al Taawon":"Al-Taawoun Buraidah",
        "Al Taee":"Al Taee",
        "Al Wehda Club":"Al-Wahda (KSA)",
        "Al-Ahli Jeddah":"Al Ahli",
        "Al-Ettifaq":"Al-Ettifaq",
        "Al-Fateh":"AL-Fetah (KSA)",
        "Al-Fayha":"Al-Feiha",
        "Al-Hazm":"Al-Hazm (KSA)",
        "Al-Hilal Saudi FC":"Al-Hilal",
        "Al-Ittihad FC":"Al-Ittihad",
        "Al-Nassr":"Al-Nassr",
        "Al-Raed":"Al-Raed (KSA)",
        "Damac":"Dhamk"
    },
    "USA": {
        "Atlanta United FC":"Atlanta Utd",
        "Austin":"Austin FC",
        "Charlotte":"Charlotte FC",
        "Chicago Fire":"Chicago Fire",
        "Colorado Rapids":"Colorado",
        "Columbus Crew":"Columbus",
        "DC United":"DC Utd",
        "FC Cincinnati":"FC Cincinnati",
        "FC Dallas":"FC Dallas",
        "Houston Dynamo":"Houston Dynamo",
        "Inter Miami":"Inter Miami CF",
        "Los Angeles FC":"Los Angeles FC",
        "Los Angeles Galaxy":"LA Galaxy",
        "Minnesota United FC":"Minnesota Utd",
        "Montreal Impact":"CF Montreal",
        "Nashville SC":"Nashville SC",
        "New England Revolution":"New England",
        "New York City FC":"New York City",
        "New York Red Bulls":"New York Red Bulls",
        "Orlando City SC":"Orlando City",
        "Philadelphia Union":"Philadelphia",
        "Portland Timbers":"Portland Timbers",
        "Real Salt Lake":"Real Salt Lake",
        "San Jose Earthquakes":"San Jose Earthquakes",
        "Seattle Sounders":"Seattle Sounders",
        "Sporting Kansas City":"Kansas City",
        "St. Louis City":"St Louis City SC",
        "Toronto FC":"Toronto FC",
        "Vancouver Whitecaps":"Vancouver Whitecaps"
    },
    "Brazil": {
        "Atletico Goianiense":"Atletico Go",
        "Atletico Paranaense":"Atletico-PR",
        "Atletico-MG":"Atletico-MG",
        "Bahia":"Bahia",
        "Botafogo":"Botafogo",
        "Corinthians":"Corinthians",
        "Criciuma":"Criciuma",
        "Cruzeiro":"Cruzeiro MG",
        "Cuiaba":"Cuiaba",
        "Flamengo":"Flamengo",
        "Fluminense":"Fluminense",
        "Fortaleza EC":"Fortaleza EC",
        "Gremio":"Gremio",
        "Internacional":"Internacional",
        "Juventude":"Juventude",
        "Palmeiras":"SE Palmeiras",
        "RB Bragantino":"Bragantino SP",
        "Sao Paulo":"Sao Paulo",
        "Vasco DA Gama":"Vasco DA Gama",
        "Vitoria":"EC Vitoria Salvador"
    },
    "Argentina": {
        "Argentinos JRS":"Argentinos Juniors",
        "Atletico Tucuman":"Atl Tucuman",
        "Banfield":"Banfield",
        "Barracas Central":"Barracas Central",
        "Belgrano Cordoba":"Belgrano",
        "Boca Juniors":"Boca Juniors",
        "Central Cordoba de Santiago":"Central Cordoba (SdE)",
        "Defensa Y Justicia":"Defensa Y Justicia",
        "Deportivo Riestra":"Deportivo Riestra",
        "Estudiantes L.P.":"Estudiantes",
        "Gimnasia L.P.":"Gimnasia La Plata",
        "Godoy Cruz":"Godoy Cruz",
        "Huracan":"Huracan",
        "Independ. Rivadavia":"Independiente Rivadavia",
        "Independiente":"CA Independiente",
        "Instituto Cordoba":"Instituto",
        "Lanus":"Lanus",
        "Newells Old Boys":"Newells",
        "Platense":"CA Platense",
        "Racing Club":"Racing Club",
        "River Plate":"River Plate",
        "Rosario Central":"Rosario Central",
        "San Lorenzo":"San Lorenzo",
        "Sarmiento Junin":"Sarmiento de Junin",
        "Talleres Cordoba":"Talleres",
        "Tigre":"Tigre",
        "Union Santa Fe":"Union Santa Fe",
        "Velez Sarsfield":"Velez Sarsfield",
    },
    "World": {
        "Albania":"Albania",
        "Austria":"Austria",
        "Belgium":"Belgium",
        "Croatia":"Croatia",
        "CzechRepublic":"Czech Republic",
        "Denmark":"Denmark",
        "England":"England",
        "France":"France",
        "Georgia":"Georgia",
        "Germany":"Germany",
        "Hungary":"Hungary",
        "Italy":"Italy",
        "Netherlands":"Netherlands",
        "Poland":"Poland",
        "Portugal":"Portugal",
        "Romania":"Romania",
        "Scotland":"Scotland",
        "Serbia":"Serbia",
        "Slovakia":"Slovakia",
        "Slovenia":"Slovenia",
        "Spain":"Spain",
        "Switzerland":"Switzerland",
        "Turkey":"Turkey",
        "Ukraine":"Ukraine"
    },
    "Scotland":{
        "Aberdeen":"Aberdeen",
        "Celtic":"Celtic",
        "Dundee":"Dundee",
        "Hearts":"Heart OF Midlothian",
        "Hibernian":"Hibernian",
        "Kilmarnock":"Kilmarnock",
        "Livingston":"Livingston",
        "Motherwell":"Motherwell",
        "Rangers":"Rangers",
        "Ross County":"Ross Co",
        "ST Johnstone":"St Johnstone",
        "ST Mirren":"St Mirren",      
    }
}