countries = {
    "Arsenal":"England",
    "Aston Villa":"England",
    "Bournemouth":"England",
    "Brentford":"England",
    "Brighton":"England",
    "Burnley":"England",
    "Chelsea":"England",
    "Crystal Palace":"England",
    "Everton":"England",
    "Fulham":"England",
    "Liverpool":"England",
    "Luton":"England",
    "Manchester City":"England",
    "Manchester United":"England",
    "Newcastle":"England",
    "Nottingham Forest":"England",
    "Sheffield Utd":"England",
    "Tottenham":"England",
    "West Ham":"England",
    "Wolves":"England",
    
    "Birmingham":"England",
    "Blackburn":"England",
    "Bristol City":"England",
    "Cardiff":"England",
    "Coventry":"England",
    "Huddersfield":"England",
    "Hull City":"England",
    "Ipswich":"England",
    "Leeds":"England",
    "Leicester":"England",
    "Middlesbrough":"England",
    "Millwall":"England",
    "Norwich":"England",
    "Plymouth":"England",
    "Preston":"England",
    "QPR":"England",
    "Rotherham":"England",
    "Sheffield Wednesday":"England",
    "Southampton":"England",
    "Stoke City":"England",
    "Sunderland":"England",
    "Swansea":"England",
    "Watford":"England",
    "West Brom":"England",


    "Barnsley":"England",
    "Blackpool":"England",
    "Bolton":"England",
    "Bristol Rovers":"England",
    "Burton Albion":"England",
    "Cambridge United":"England",
    "Carlisle":"England",
    "Charlton":"England",
    "Cheltenham":"England",
    "Derby":"England",
    "Exeter City":"England",
    "Fleetwood Town":"England",
    "Leyton Orient":"England",
    "Lincoln":"England",
    "Northampton":"England",
    "Oxford United":"England",
    "Peterborough":"England",
    "Port Vale":"England",
    "Portsmouth":"England",
    "Reading":"England",
    "Shrewsbury":"England",
    "Stevenage":"England",
    "Wigan":"England",
    "Wycombe":"England",


    "Alaves":"Spain",
    "Almeria":"Spain",
    "Athletic Club":"Spain",
    "Atletico Madrid":"Spain",
    "Barcelona":"Spain",
    "Cadiz":"Spain",
    "Celta Vigo":"Spain",
    "Getafe":"Spain",
    "Girona":"Spain",
    "Granada CF":"Spain",
    "Las Palmas":"Spain",
    "Mallorca":"Spain",
    "Osasuna":"Spain",
    "Rayo Vallecano":"Spain",
    "Real Betis":"Spain",
    "Real Madrid":"Spain",
    "Real Sociedad":"Spain",
    "Sevilla":"Spain",
    "Valencia":"Spain",
    "Villarreal":"Spain",


    "AC Milan":"Italy",
    "AS Roma":"Italy",
    "Atalanta":"Italy",
    "Bologna":"Italy",
    "Cagliari":"Italy",
    "Empoli":"Italy",
    "Fiorentina":"Italy",
    "Frosinone":"Italy",
    "Genoa":"Italy",
    "Inter":"Italy",
    "Juventus":"Italy",
    "Lazio":"Italy",
    "Lecce":"Italy",
    "Monza":"Italy",
    "Napoli":"Italy",
    "Salernitana":"Italy",
    "Sassuolo":"Italy",
    "Torino":"Italy",
    "Udinese":"Italy",
    "Verona":"Italy",


    "1.FC Köln":"Germany",
    "1899 Hoffenheim":"Germany",
    "Bayer Leverkusen":"Germany",
    "Bayern Munich":"Germany",
    "Borussia Dortmund":"Germany",
    "Borussia Monchengladbach":"Germany",
    "Eintracht Frankfurt":"Germany",
    "FC Augsburg":"Germany",
    "FC Heidenheim":"Germany",
    "FSV Mainz 05":"Germany",
    "RB Leipzig":"Germany",
    "SC Freiburg":"Germany",
    "SV Darmstadt 98":"Germany",
    "Union Berlin":"Germany",
    "VfB Stuttgart":"Germany",
    "Vfl Bochum":"Germany",
    "VfL Wolfsburg":"Germany",
    "Werder Bremen":"Germany",


    "Clermont Foot":"France",
    "LE Havre":"France",
    "Lens":"France",
    "Lille":"France",
    "Lorient":"France",
    "Lyon":"France",
    "Marseille":"France",
    "Metz":"France",
    "Monaco":"France",
    "Montpellier":"France",
    "Nantes":"France",
    "Nice":"France",
    "Paris Saint Germain":"France",
    "Reims":"France",
    "Rennes":"France",
    "Stade Brestois 29":"France",
    "Strasbourg":"France",
    "Toulouse":"France"

}

teams = {
    "England": {
        "Arsenal":"Arsenal",
        "Aston Villa":"Aston Villa",
        "Bournemouth":"Bournemouth",
        "Brentford":"Brentford",
        "Brighton":"Brighton",
        "Burnley":"Burnley",
        "Chelsea":"Chelsea",
        "Crystal Palace":"Crystal Palace",
        "Everton":"Everton",
        "Fulham":"Fulham",
        "Liverpool":"Liverpool",
        "Luton":"Luton",
        "Manchester City":"Man City",
        "Manchester United":"Man Utd",
        "Newcastle":"Newcastle",
        "Nottingham Forest":"Nottm Forest",
        "Sheffield Utd":"Sheff Utd",
        "Tottenham":"Tottenham",
        "West Ham":"West Ham",
        "Wolves":"Wolves",
        
        "Birmingham":"Birmingham",
        "Blackburn":"Blackburn",
        "Bristol City":"Bristol City",
        "Cardiff":"Cardiff",
        "Coventry":"Coventry",
        "Huddersfield":"Huddersfield",
        "Hull City":"Hull",
        "Ipswich":"Ipswich",
        "Leeds":"Leeds",
        "Leicester":"Leicester",
        "Middlesbrough":"Middlesbrough",
        "Millwall":"Millwall",
        "Norwich":"Norwich",
        "Plymouth":"Plymouth",
        "Preston":"Preston",
        "QPR":"QPR",
        "Rotherham":"Rotherham",
        "Sheffield Wednesday":"Sheff Wed",
        "Southampton":"Southampton",
        "Stoke City":"Stoke",
        "Sunderland":"Sunderland",
        "Swansea":"Swansea",
        "Watford":"Watford",
        "West Brom":"West Brom",

        "Barnsley":"Barnsley",
        "Blackpool":"Blackpool",
        "Bolton":"Bolton",
        "Bristol Rovers":"Bristol Rovers",
        "Burton Albion":"Burton Albion",
        "Cambridge United":"Cambridge Utd",
        "Carlisle":"Carlisle",
        "Charlton":"Charlton",
        "Cheltenham":"Cheltenham",
        "Derby":"Derby",
        "Exeter City":"Exeter",
        "Fleetwood Town":"Fleetwood Town",
        "Leyton Orient":"Leyton Orient",
        "Lincoln":"Lincoln",
        "Northampton":"Northampton",
        "Oxford United":"Oxford Utd",
        "Peterborough":"Peterborough",
        "Port Vale":"Port Vale",
        "Portsmouth":"Portsmouth",
        "Reading":"Reading",
        "Shrewsbury":"Shrewsbury",
        "Stevenage":"Stevenage",
        "Wigan":"Wigan",
        "Wycombe":"Wycombe"
    },
    "Italy": {
        "AC Milan":"AC Milan",
        "AS Roma":"Roma",
        "Atalanta":"Atalanta",
        "Bologna":"Bologna",
        "Cagliari":"Cagliari",
        "Empoli":"Empoli",
        "Fiorentina":"Fiorentina",
        "Frosinone":"Frosinone",
        "Genoa":"Genoa",
        "Inter":"Inter",
        "Juventus":"Juventus",
        "Lazio":"Lazio",
        "Lecce":"Lecce",
        "Monza":"AC Monza",
        "Napoli":"Napoli",
        "Salernitana":"Salernitana",
        "Sassuolo":"Sassuolo",
        "Torino":"Torino",
        "Udinese":"Udinese",
        "Verona":"Verona"
    },
    "Spain": {
        "Alaves":"Alaves",
        "Almeria":"Almeria",
        "Athletic Club":"Athletic Bilbao",
        "Atletico Madrid":"Atletico Madrid",
        "Barcelona":"Barcelona",
        "Cadiz":"Cadiz",
        "Celta Vigo":"Celta Vigo",
        "Getafe":"Getafe",
        "Girona":"Girona",
        "Granada CF":"Granada",
        "Las Palmas":"Las Palmas",
        "Mallorca":"Mallorca",
        "Osasuna":"Osasuna",
        "Rayo Vallecano":"Rayo Vallecano",
        "Real Betis":"Betis",
        "Real Madrid":"Real Madrid",
        "Real Sociedad":"Real Sociedad",
        "Sevilla":"Sevilla",
        "Valencia":"Valencia",
        "Villarreal":"Villarreal"
    },
    "Germany": {
        "1.FC Köln":"FC Koln",
        "1899 Hoffenheim":"Hoffenheim",
        "Bayer Leverkusen":"Leverkusen",
        "Bayern Munich":"Bayern Munich",
        "Borussia Dortmund":"Dortmund",
        "Borussia Monchengladbach":"Mgladbach",
        "Eintracht Frankfurt":"Eintracht Frankfurt",
        "FC Augsburg":"Augsburg",
        "FC Heidenheim":"FC Heidenheim",
        "FSV Mainz 05":"Mainz",
        "RB Leipzig":"RB Leipzig",
        "SC Freiburg":"Freiburg",
        "SV Darmstadt 98":"SV Darmstadt",
        "Union Berlin":"Union Berlin",
        "VfB Stuttgart":"Stuttgart",
        "Vfl Bochum":"Bochum",
        "VfL Wolfsburg":"Wolfsburg",
        "Werder Bremen":"Bremen"
    },
    "France": {
        "Clermont Foot":"Clermont",
        "LE Havre":"Havre",
        "Lens":"Lens",
        "Lille":"Lille",
        "Lorient":"Lorient",
        "Lyon":"Lyon",
        "Marseille":"Marseille",
        "Metz":"Metz",
        "Monaco":"Monaco",
        "Montpellier":"Montpellier",
        "Nantes":"Nantes",
        "Nice":"Nice",
        "Paris Saint Germain":"Paris St-G",
        "Reims":"Reims",
        "Rennes":"Rennes",
        "Stade Brestois 29":"Brest",
        "Strasbourg":"Strasbourg",
        "Toulouse":"Toulouse"
    }
}